- id: doi:10.1158/2159-8290.CD-22-0111
  type: paper
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerdiscovery/12/11/10.1158_2159-8290.cd-22-0111/3/m_2666fig1.jpeg?Expires=1681214687&Signature=mwsUxMpvii84tjc2sF5RvrSsMzkVbKQS9NKTv66npKJzxbn01VRt36DU2ip9ZlXHgHmXXAuwJrLXUfd~cm14CJlUoo7WirIWRBmfqb1lYD-AGetb~3yAXxezhG-GrX1~TcRmiCCf7DpJNQnsFB6G5jmEgbxWy5B4VM~wFZ7uAsLG7CAJP17IFcSvIy~OCdWy41zyDcxf5Sy-KbwqypfsErSvdRMBKXZZpbCgs2JqQAvvGaI-fJsBqo7tYl07wg0Q4O3BJceR7VK9Innjc5gzbtmVP7Vh5C9GSv5rUuXzq~mDWkf1LKmEfuE5yh-iKNzhgLGYffbcOM6MR30eatTg5A__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1016/j.cell.2021.03.030
  type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0092867421003615-fx1.jpg
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
  tags:
    - synthetic lethality
    - cancer therapy
    - precision medicine
  repo: NEXGEM/SELECT

- id: doi:10.1038/s41467-018-04647-1
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-018-04647-1/MediaObjects/41467_2018_4647_Fig1_HTML.jpg?as=webp

- id: doi:10.1001/jamaoncol.2019.2311
  type: paper
  image: https://cdn.jamanetwork.com/ama/content_public/journal/oncology/938270/cbr190007f1.png?Expires=1682004390&Signature=XTp2ZHqY787p4upKcKjb7af99L2ChqPLANq66Btjo7OhbLxjpxCcqNY2ZphPUl3t2iTGPs3HjAAConNnFnRiUnSHQK80hiiiFiTBrGKxC-I2oaX4VrtOxTGL~YGucVW1yEBoJyvhXaW-BVVouk565cDMiUcHHPbGIkGZ1gRxP8XQ7oUiB4iduaLsCrZiozoGvpTbOSUMV~Apy-wpuIcvQ6xB3WZ~AnoYVMeLIBRVoORUKSACdI07CEqq6y8M5FMuEUQVjB3p5vuh1fT9PQusHYi4eO9N-xbKN-JLqwcwHzRtPz-zHxhePR7qXTVpXUOqjWHo55JTquQEDkWbELS-EQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
